Add doc for Bum traffic
Ragarnoy/BADASS pull request #45
Opened 2022-10-04 17:39 UTC by FirelightFlagboy

2022-10-05 13:15 UTC, Eviber approved these changes

2022-10-09 17:09 UTC, Ragarnoy requested changes

2022-10-09 17:09 UTC, Ragarnoy commented on docs/what-is-bum.md
> +`BUM traffic` is any network traffic transmitted using one of the three methods listed above to an destination where its address is **Unknown**.
```suggestion
`BUM traffic` is any network traffic transmitted using one of the three methods listed above to a destination when its address is **Unknown**.
```

2022-10-09 17:18 UTC, Ragarnoy approved these changes

2022-10-09 17:18 UTC, merged