Create what-is-a-network-switch.md
Ragarnoy/BADASS pull request #48
Opened 2022-10-06 17:03 UTC by Eviber

closes #31

2022-10-06 18:02 UTC, FirelightFlagboy requested changes
Do we want to add a section for *dump* and *smart* switches ?

2022-10-06 18:02 UTC, FirelightFlagboy commented on docs/what-is-a-network-switch.md
> +Switches can operate on the layer 2 (via MAC addresses) or the layer 3 (via IP). Though some can do both, most switches are layer 2 switches.
```suggestion

Switches can operate on the layer 2 (via MAC addresses) or the layer 3 (via IP). Though some can do both, most switches are layer 2 switches.
```

2022-10-06 18:02 UTC, FirelightFlagboy commented on docs/what-is-a-network-switch.md
> +The way it can forward packets to the desired device is by keeping a table called CAM (Content Addressable Memory) table.
```suggestion

The way it can forward packets to the desired device is by keeping a table called CAM (Content Addressable Memory) table.
```

2022-10-06 19:41 UTC, Eviber commented
I added a section about unmanaged vs managed switches.

2022-10-07 07:03 UTC, FirelightFlagboy approved these changes

2022-10-09 17:10 UTC, Ragarnoy approved these changes

2022-10-09 17:19 UTC, merged